# Default values for platform-auth.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
global:
  authGlobalDefinition:
    name: auth-global
    enabled: true
    image:
      registry: "docker.io"
      organization: exastro
      package: exastro-platform
    config:
      DEFAULT_LANGUAGE: "ja"
      LANGUAGE: "en"
      TZ: "Asia/Tokyo"
      PYTHONIOENCODING: utf-8
      PLATFORM_API_PROTOCOL: "http"
      PLATFORM_API_HOST: "platform-api"
      PLATFORM_API_PORT: "8000"
      PLATFORM_WEB_PROTOCOL: "http"
      PLATFORM_WEB_HOST: "platform-web"
      PLATFORM_WEB_PORT: "8000"
    secret:
      ENCRYPT_KEY: ""
    persistence:
      enabled: true
      accessMode: ReadWriteMany
      size: 10Gi
      volumeType: hostPath # e.g.) hostPath or AKS
      storageClass: "-" # e.g.) azurefile or - (None)
      # matchLabels:
      #   release: "stable"
      # matchExpressions:
      #   - {key: environment, operator: In, values: [dev]}
  keycloakDefinition:
    name: keycloak
    enabled: true
    config:
      API_KEYCLOAK_PROTOCOL: "http"
      API_KEYCLOAK_HOST: "keycloak.exastro-platform.svc"
      API_KEYCLOAK_PORT: "8080"
      KEYCLOAK_PROTOCOL: "http"
      KEYCLOAK_HOST: "keycloak.exastro-platform.svc"
      KEYCLOAK_PORT: "8080"
      KEYCLOAK_MASTER_REALM: "master"
      KEYCLOAK_DB_DATABASE: "keycloak"
    secret:
      KEYCLOAK_USER: ""
      KEYCLOAK_PASSWORD: ""
      KEYCLOAK_DB_USER: ""
      KEYCLOAK_DB_PASSWORD: ""
  itaDefinition:
    name: ita
    enabled: true
    config:
      ITA_WEB_PROTOCOL: "http"
      ITA_WEB_HOST: "ita-web-server.exastro-it-automation.svc"
      ITA_WEB_PORT: "8000"
      ITA_API_PROTOCOL: "http"
      ITA_API_HOST: "ita-api-organization.exastro-it-automation.svc"
      ITA_API_PORT: "8080"
      ITA_API_ADMIN_PROTOCOL: "http"
      ITA_API_ADMIN_HOST: "ita-api-admin.exastro-it-automation.svc"
      ITA_API_ADMIN_PORT: "8080"
  authDatabaseDefinition:
    name: auth-database
    enabled: true
    config:
      DB_VENDOR: "mariadb"
      DB_HOST: "mariadb.exastro-platform.svc"
      DB_PORT: "3306"
      DB_DATABASE: "platform"
    secret:
      DB_ADMIN_USER: ""
      DB_ADMIN_PASSWORD: ""
      DB_USER: ""
      DB_PASSWORD: ""

extraEnv:
  PLATFORM_AUTH_PROTOCOL: "http"
  PLATFORM_AUTH_HOST: "platform-auth"
  PLATFORM_AUTH_PORT: "8000"
  LISTEN_PORT: "8000"
  LISTEN_PORT_PF_MNG: "8001"

replicaCount: 1

initContainerImage:
  repository: busybox
  tag: ""
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.

image:
  repository: ""
  tag: ""
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: false
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

persistence:
  mountPath:
    storage: /storage
    homeDir: /home/app_user
    pid:
      path: /var/run_app_user/httpd/pid
      subPath: httpd-pid
    socket:
      path: /var/run_app_user/httpd/socket
      subPath: httpd-socket
    tmp: /tmp

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext:
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true
  runAsUser: 1000
  runAsGroup: 1000
  runAsNonRoot: true

service:
  type: ClusterIP
  http:
    name: http
    port: 8000
    # nodePort: 30080
  httpMng:
    name: http-pf-mng
    port: 8001
    # nodePort: 30081

ingress:
  enabled: true
  name: "platform-auth"
  className: ""
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: exastro-suite.example.local
      paths:
        - path: /
          pathType: Prefix
          backend: "http"
    - host: exastro-suite-mng.example.local
      paths:
        - path: /
          pathType: Prefix
          backend: "httpMng"
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: {}
  # requests:
  #   memory: "64Mi"
  #   cpu: "250m"
  # limits:
  #   memory: "64Mi"
  #   cpu: "250m"

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
