#   Copyright 2022 NEC Corporation
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.
apiVersion: v1
kind: ConfigMap
metadata:
  name: keycloak
  namespace: exastro-platform
data:
  API_KEYCLOAK_PROTOCOL: "http"
  API_KEYCLOAK_HOST: "keycloak"
  API_KEYCLOAK_PORT: "8080"
  KEYCLOAK_PROTOCOL: "http"
  KEYCLOAK_HOST: "keycloak"
  KEYCLOAK_PORT: "8080"
  KEYCLOAK_MASTER_REALM: "master"
  KEYCLOAK_DB_DATABASE: "keycloak"

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  labels:
    app: keycloak
  namespace: exastro-platform
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
        - name: keycloak
          image: exastro/exastro-common-auth-keycloak:0.1.0.47d4d2.20220825-163604
          ports:
            - name: http
              containerPort: 8080
          env:
            - name: KEYCLOAK_USER
              valueFrom:
                secretKeyRef:
                  name: keycloak
                  key: KEYCLOAK_USER
            - name: KEYCLOAK_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: keycloak
                  key: KEYCLOAK_PASSWORD
            - name: PROXY_ADDRESS_FORWARDING
              value: "true"
            - name: DB_VENDOR
              valueFrom:
                configMapKeyRef:
                  name: platform-db
                  key: DB_VENDOR
            - name: DB_ADDR
              valueFrom:
                configMapKeyRef:
                  name: platform-db
                  key: DB_ADDR
            - name: DB_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: keycloak
                  key: KEYCLOAK_DB_DATABASE
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: keycloak
                  key: KEYCLOAK_DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: keycloak
                  key: KEYCLOAK_DB_PASSWORD
          readinessProbe:
            httpGet:
              path: /auth/realms/master
              port: 8080
