#   Copyright 2022 NEC Corporation
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.
apiVersion: v1
kind: ConfigMap
metadata:
  name: platform-db
  namespace: exastro-platform
data:
  DB_VENDOR: "mariadb"
  DB_ADDR: "platform-db"
  DB_PORT: "3306"
  PLATFORM_DB_DATABASE: "platform"

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: platform-db
  labels:
    app: platform-db
  namespace: exastro-platform
spec:
  replicas: 1
  selector:
    matchLabels:
      app: platform-db
  template:
    metadata:
      labels:
        app: platform-db
    spec:
      containers:
        - name: platform-db
          image: exastro/exastro-common-auth-platform-db:Integration-test.83aff2.20220912-164019
          ports:
            - name: mariadb
              containerPort: 3306
          env:
          - name: TZ
            valueFrom:
              configMapKeyRef:
                name: params-platform-common
                key: TZ
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: platform-db
                key: MYSQL_ROOT_PASSWORD
          - name: KEYCLOAK_DB_DATABASE
            valueFrom:
              configMapKeyRef:
                name: keycloak
                key: KEYCLOAK_DB_DATABASE
          - name: KEYCLOAK_DB_USER
            valueFrom:
              secretKeyRef:
                name: keycloak
                key: KEYCLOAK_DB_USER
          - name: KEYCLOAK_DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: keycloak
                key: KEYCLOAK_DB_PASSWORD
          - name: PLATFORM_DB_DATABASE
            valueFrom:
              configMapKeyRef:
                name: platform-db
                key: PLATFORM_DB_DATABASE
          - name: PLATFORM_DB_USER
            valueFrom:
              secretKeyRef:
                name: platform-db
                key: PLATFORM_DB_USER
          - name: PLATFORM_DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: platform-db
                key: PLATFORM_DB_PASSWORD
          volumeMounts:
            - name: persistent-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: persistent-storage
          persistentVolumeClaim:
            claimName: platform-db
