#   Copyright 2022 NEC Corporation
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.
apiVersion: v1
kind: ConfigMap
metadata:
  name: platform-web
  namespace: exastro-platform
data:
  PLATFORM_WEB_PROTOCOL: "http"
  PLATFORM_WEB_HOST: "platform-web"
  PLATFORM_WEB_PORT: "8000"
  LISTEN_PORT: "8000"

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: platform-web
  namespace: exastro-platform
spec:
  selector:
    matchLabels:
      name: platform-web
  replicas: 1
  template:
    metadata:
      labels:
        name: platform-web
    spec:
      containers:
      - name: platform-web
        image: exastro/exastro-common-auth-platform-web:0.1.0.47d4d2.20220825-163559
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          runAsUser: 1000
          runAsGroup: 1000
          runAsNonRoot: true
        volumeMounts:
        - name: contaier-volume
          mountPath: /var/run_app_user/httpd/pid
          subPath: httpd-pid
        - name: contaier-volume
          mountPath: /var/run_app_user/httpd/socket
          subPath: httpd-socket
        env:
        - name: LISTEN_PORT
          valueFrom:
            configMapKeyRef:
              name: platform-web
              key: LISTEN_PORT
      volumes:
      - name: contaier-volume
        emptyDir: {}
