#   Copyright 2022 NEC Corporation
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.

openapi: 3.0.3

info:
  title: Exastro Platform API
  description: Exastro Platform API
  version: 1.2.0

servers:
- url: /

tags:
- name: OrganizationService
  description: オーガナイゼーションに関する操作
- name: PlanService
  description: プランに関する操作
- name: WorkspaceService
  description: ワークスペースに関する操作
- name: UsersService
  description: ユーザーに関する操作
- name: RoleService
  description: ロールに関する操作
- name: RoleMappingsService
  description: ロール・マッピングに関する操作
- name: InternalCommonService
  description: 共通(内部用)
- name: InternalUsersService
  description: ユーザーに関する操作(内部用)
- name: InternalWorkspaceService
  description: ワークスペースに関する操作(内部用)

paths:
  "/api/platform/organizations":
      $ref: './paths/organizations.yaml'

  "/api/platform/{organization_id}/plans":
      $ref: './paths/plans.organizations.yaml'
  "/api/platform/{organization_id}/plans/{plan_start_date}":
      $ref: './paths/plans.organizations.plan_start_date.yaml'
  "/api/platform/plans":
      $ref: './paths/plans.yaml'
  "/api/platform/limits":
      $ref: './paths/limits.yaml'

  "/api/{organization_id}/platform/workspaces":
      $ref: './paths/workspaces.yaml'
  "/api/{organization_id}/platform/workspaces/{workspace_id}":
      $ref: './paths/workspaces.workspace_id.yaml'
  "/api/{organization_id}/platform/workspaces/{workspace_id}/members":
      $ref: './paths/workspaces.workspace_id.members.yaml'

  "/api/{organization_id}/platform/users":
      $ref: './paths/users.yaml'

  "/api/{organization_id}/platform/roles":
      $ref: './paths/roles.yaml'
  "/api/{organization_id}/platform/roles/{role_name}":
      $ref: './paths/roles.role_name.yaml'

  "/api/{organization_id}/platform/roles/{role_name}/users":
      $ref: './paths/roles.role_name.users.yaml'

  "/internal-api/{organization_id}/platform/workspaces/{workspace_id}/roles":
      $ref: './paths/internal_workspaces.workspace_id.roles.yaml'
  "/internal-api/{organization_id}/platform/workspaces/{workspace_id}/users":
      $ref: './paths/internal_workspaces.workspace_id.users.yaml'
  "/internal-api/{organization_id}/platform/users/{user_id}/workspaces":
      $ref: './paths/internal_users.user_id.workspaces.yaml'

  "/internal-api/alive":
      $ref: './paths/internal_alive.yaml'

components:
  schemas:
    $ref: './schemas/_schemas.yaml'
