#   Copyright 2022 NEC Corporation
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.

openapi: 3.0.3

info:
  title: Exastro Platform API
  description: Exastro Platform API
  version: 1.3.0

servers:
  - url: "https://{host}"
    description: API endpoint
    variables:
      host:
        default: localhost
  - url: "http://{host}"
    description: API endpoint
    variables:
      host:
        default: localhost
  - url: "{protocol}://{host}:{port}"
    description: API endpoint (Development)
    variables:
      protocol:
        enum:
          - http
          - https
        default: https
      host:
        default: localhost
      port:
        default: '30080'

tags:
- name: OrganizationService
  description: オーガナイゼーションに関する操作
- name: TokenService
  description: tokenに関する操作
- name: PlanService
  description: プランに関する操作
- name: UsageService
  description: リソース使用量に関する操作
- name: WorkspaceService
  description: ワークスペースに関する操作
- name: UsersService
  description: ユーザーに関する操作
- name: RoleService
  description: ロールに関する操作
- name: RoleMappingsService
  description: ロール・マッピングに関する操作
- name: InternalCommonService
  description: 共通(内部用)
- name: InternalPlanService
  description: プランに関する操作(内部用)
- name: InternalUsersService
  description: ユーザーに関する操作(内部用)
- name: InternalWorkspaceService
  description: ワークスペースに関する操作(内部用)

paths:
  "/api/platform/organizations":
      $ref: './paths/organizations.yaml'
  "/api/{organization_id}/platform/setting":
      $ref: './paths/organization.setting.yaml'

  "/auth/realms/{organization_id}/protocol/openid-connect/token":
      $ref: './paths/protocol.openid-connect.token.yaml'
  "/api/{organization_id}/platform/users/_current/refresh_tokens":
      $ref: './paths/user.current.refresh_tokens.yaml'
  "/api/platform/users/_current/refresh_tokens":
      $ref: './paths/user.current.refresh_tokens.platform.yaml'


  "/api/platform/{organization_id}/plans":
      $ref: './paths/plans.organizations.yaml'
  "/api/platform/{organization_id}/plans/{plan_start_datetime}":
      $ref: './paths/plans.organizations.plan_start_datetime.yaml'
  "/api/platform/plans":
      $ref: './paths/plans.yaml'
  "/api/platform/plan_items":
      $ref: './paths/plan_items.yaml'
  "/api/{organization_id}/platform/limits":
      $ref: './paths/plans.organizations.limits.yaml'

  "/api/platform/usages":
      $ref: './paths/usages.yaml'
  "/api/{organization_id}/platform/usages":
      $ref: './paths/usages.organizations.yaml'

  "/api/{organization_id}/platform/workspaces":
      $ref: './paths/workspaces.yaml'
  "/api/{organization_id}/platform/workspaces/{workspace_id}":
      $ref: './paths/workspaces.workspace_id.yaml'
  "/api/{organization_id}/platform/workspaces/{workspace_id}/members":
      $ref: './paths/workspaces.workspace_id.members.yaml'

  "/api/{organization_id}/platform/users":
      $ref: './paths/users.yaml'

  "/api/{organization_id}/platform/roles":
      $ref: './paths/roles.yaml'
  "/api/{organization_id}/platform/roles/{role_name}":
      $ref: './paths/roles.role_name.yaml'

  "/api/{organization_id}/platform/roles/{role_name}/users":
      $ref: './paths/roles.role_name.users.yaml'

  "/internal-api/{organization_id}/platform/limits":
      $ref: './paths/internal_plans.organizations.limits.yaml'
  "/internal-api/platform/limits":
      $ref: './paths/internal_plan.limits.yaml'

  "/internal-api/{organization_id}/platform/workspaces/{workspace_id}/roles":
      $ref: './paths/internal_workspaces.workspace_id.roles.yaml'
  "/internal-api/{organization_id}/platform/workspaces/{workspace_id}/users":
      $ref: './paths/internal_workspaces.workspace_id.users.yaml'
  "/internal-api/{organization_id}/platform/users/{user_id}/workspaces":
      $ref: './paths/internal_users.user_id.workspaces.yaml'

  "/internal-api/alive":
      $ref: './paths/internal_alive.yaml'

components:
  schemas:
    $ref: './schemas/_schemas.yaml'

  securitySchemes:
    BearerAuth:
      description: Credentials or access token for API
      type: http
      scheme: bearer
      bearerFormat: JWT
    BasicAuth:
      description: Value converted from ID/Password in base64
      type: http
      scheme: basic

  responses:
    UnauthorizedError:
      description: Access token is missing or invalid

security:
- BearerAuth: []
- BasicAuth: []