# Default values for platform-api.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
global:
  authGlobalDefinition:
    name: auth-global
    enabled: true
    image:
      registry: "docker.io"
      organization: exastro
      package: exastro-platform
    config:
      DEFAULT_LANGUAGE: "ja"
      LANGUAGE: "en"
      TZ: "Asia/Tokyo"
      PYTHONIOENCODING: utf-8
      PLATFORM_API_PROTOCOL: "http"
      PLATFORM_API_HOST: "platform-auth"
      PLATFORM_API_PORT: "8000"
      PLATFORM_WEB_PROTOCOL: "http"
      PLATFORM_WEB_HOST: "platform-web"
      PLATFORM_WEB_PORT: "8000"
    persistence:
      enabled: true
      accessMode: ReadWriteMany
      size: 10Gi
      volumeType: hostPath # e.g.) hostPath or AKS
      storageClass: "-" # e.g.) azurefile or - (None)
      # matchLabels: 
      #   release: "stable"
      # matchExpressions:
      #   - {key: environment, operator: In, values: [dev]}
  keycloakDefinition:
    name: keycloak
    enabled: true
    config:
      API_KEYCLOAK_PROTOCOL: "http"
      API_KEYCLOAK_HOST: "keycloak.exastro-platform.svc"
      API_KEYCLOAK_PORT: "8080"
      KEYCLOAK_PROTOCOL: "http"
      KEYCLOAK_HOST: "keycloak.exastro-platform.svc"
      KEYCLOAK_PORT: "8080"
      KEYCLOAK_MASTER_REALM: "master"
      KEYCLOAK_DB_DATABASE: "keycloak"
    secret:
      KEYCLOAK_USER: ""
      KEYCLOAK_PASSWORD: ""
      KEYCLOAK_DB_USER: ""
      KEYCLOAK_DB_PASSWORD: ""
  itaDefinition:
    name: ita
    enabled: true
    config:
      ITA_WEB_PROTOCOL: "http"
      ITA_WEB_HOST: "ita-web-server.exastro-it-automation.svc"
      ITA_WEB_PORT: "8000"
      ITA_API_PROTOCOL: "http"
      ITA_API_HOST: "ita-api-organization.exastro-it-automation.svc"
      ITA_API_PORT: "8080"
      ITA_API_ADMIN_PROTOCOL: "http"
      ITA_API_ADMIN_HOST: "ita-api-admin.exastro-it-automation.svc"
      ITA_API_ADMIN_PORT: "8080"
  authDatabaseDefinition:
    name: auth-database
    enabled: true
    config:
      DB_VENDOR: "mariadb"
      DB_HOST: "mariadb.exastro-platform.svc"
      DB_PORT: "3306"
      DB_DATABASE: "platform"
    secret:
      DB_ROOT_PASSWORD: ""
      DB_USER: ""
      DB_PASSWORD: ""
  databaseDefinition:
    name: mariadb
    enabled: true
    secret:
      MARIADB_ROOT_PASSWORD: ""
    persistence:
      enabled: true
      reinstall: false
      accessMode: ReadWriteOnce
      size: 20Gi
      volumeType: hostPath # e.g.) hostPath or AKS
      storageClass: "-" # e.g.) azurefile or - (None)
      # matchLabels: 
      #   release: "stable"
      # matchExpressions:
      #   - {key: environment, operator: In, values: [dev]}

ingress:
  enabled: false

service:
  type: ClusterIP

platform-api:
  image:
    repository: ""
    tag: ""

platform-auth:
  image:
    repository: ""
    tag: ""

platform-setup:
  image:
    repository: ""
    tag: ""

platform-web:
  image:
    repository: ""
    tag: ""

mariadb:
  image:
    repository: "mariadb"
    tag: "10.9"
    pullPolicy: IfNotPresent

keycloak:
  image:
    repository: "exastro/exastro-common-auth-keycloak"
    tag: "Integration-test.83aff2.20220912-164136"
    pullPolicy: IfNotPresent
