#   Copyright 2023 NEC Corporation
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.

title: destinations conditions resource.
type: object
properties:
  ita:
    type: object
    description: Exastro IT Automation conditions
    properties:
      event_type:
        type: object
        description: event type
        properties:
          new:
            type: boolean
            description: Whether to be notified of new events before evaluation
          evaluated:
            type: boolean
            description: Whether to be notified of known events upon evaluation
          timeout:
            type: boolean
            description: Whether to be notified of known events upon TTL timeout
          undetected:
            type: boolean
            description: Whether to be notified of undetected events upon evaluation
          new_received:
            type: boolean
            description: Whether to be notified of new events upon reception
          new_consolidated:
            type: boolean
            description: Whether to be notified of new events upon consolidation
        required:
          - new
          - evaluated
          - timeout
          - undetected
          - new_received
          - new_consolidated
    required:
      - event_type
required:
  - ita
